"""empty message

Revision ID: 11322380f17c
Revises: 
Create Date: 2022-08-09 12:31:45.143969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11322380f17c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('ability1', sa.String(length=20), nullable=True),
    sa.Column('ability2', sa.String(length=20), nullable=True),
    sa.Column('statName1', sa.String(length=20), nullable=True),
    sa.Column('statValue1', sa.Integer(), nullable=True),
    sa.Column('statName2', sa.String(length=20), nullable=True),
    sa.Column('statValue2', sa.Integer(), nullable=True),
    sa.Column('statName3', sa.String(length=20), nullable=True),
    sa.Column('statValue3', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('sprite', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('association',
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.Column('Pokemon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('user')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
